# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - aCR-basix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrregbasix.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7859418be2d84f9b80ae317c1cc81e2e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c2b7cf007c3b4094a4f9ff57ceba5115 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acrregbasix.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7859418be2d84f9b80ae317c1cc81e2e }}/hello-world:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aCR-basix'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_99b2b6ed3c5448018868888ddf00f74f }}
        images: 'acrregbasix.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7859418be2d84f9b80ae317c1cc81e2e }}/hello-world:${{ github.sha }}'